# Generated by Django 4.1 on 2023-02-27 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_godown_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock_item_voucher',
            old_name='Particulars',
            new_name='ledger_account',
        ),
        migrations.AddField(
            model_name='credit_note',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.voucher'),
        ),
        migrations.AddField(
            model_name='stock_item_voucher',
            name='party_account',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stock_item_voucher',
            name='Voucher_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
