# Generated by Django 4.1 on 2023-02-27 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_rename_particulars_stock_item_voucher_ledger_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit_note',
            name='voucher',
        ),
        migrations.AddField(
            model_name='credit_item',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.voucher'),
        ),
    ]
