# Generated by Django 4.1 on 2023-02-28 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_remove_credit_note_voucher_credit_item_voucher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit_item',
            name='voucher',
        ),
        migrations.AddField(
            model_name='credit_note',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.voucher'),
        ),
    ]
