# Generated by Django 4.1 on 2023-02-28 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_remove_credit_item_voucher_credit_note_voucher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit_note',
            name='comp',
        ),
        migrations.RemoveField(
            model_name='credit_note',
            name='voucher',
        ),
        migrations.DeleteModel(
            name='credit_item',
        ),
        migrations.DeleteModel(
            name='credit_note',
        ),
    ]
