# Generated by Django 4.1 on 2023-03-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0034_payment_particulars_ac_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_particulars',
            name='particular_id',
            field=models.IntegerField(null=True),
        ),
    ]
