# Generated by Django 4.1 on 2023-03-01 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0035_payment_particulars_particular_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_particulars',
            name='ac_no',
        ),
        migrations.RemoveField(
            model_name='payment_particulars',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='payment_particulars',
            name='ifscode',
        ),
        migrations.RemoveField(
            model_name='payment_particulars',
            name='inst_date',
        ),
        migrations.RemoveField(
            model_name='payment_particulars',
            name='inst_no',
        ),
        migrations.RemoveField(
            model_name='payment_particulars',
            name='transcation_type',
        ),
        migrations.AddField(
            model_name='bank_transcations',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.payment_voucher'),
        ),
    ]
