# Generated by Django 4.1 on 2023-03-06 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0036_remove_payment_particulars_ac_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank_transcations',
            name='voucher',
        ),
        migrations.AddField(
            model_name='bank_transcations',
            name='pay_particular',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.payment_particulars'),
        ),
        migrations.CreateModel(
            name='receipt_particulars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particular_id', models.IntegerField(null=True)),
                ('particular', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('rec_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.receipt_voucher')),
            ],
        ),
        migrations.AddField(
            model_name='bank_transcations',
            name='rec_particular',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.receipt_particulars'),
        ),
    ]
