# Generated by Django 4.1 on 2023-03-06 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0037_remove_bank_transcations_voucher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_transcations',
            name='pay_voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.payment_voucher'),
        ),
        migrations.AddField(
            model_name='bank_transcations',
            name='rec_voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.receipt_voucher'),
        ),
    ]
