# Generated by Django 4.1 on 2023-03-06 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0040_alter_bank_transcations_pay_particular_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bank_transcations',
        ),
        migrations.RemoveField(
            model_name='payment_voucher',
            name='voucher',
        ),
        migrations.RemoveField(
            model_name='receipt_particulars',
            name='rec_voucher',
        ),
        migrations.RemoveField(
            model_name='receipt_voucher',
            name='voucher',
        ),
        migrations.DeleteModel(
            name='payment_particulars',
        ),
        migrations.DeleteModel(
            name='payment_voucher',
        ),
        migrations.DeleteModel(
            name='receipt_particulars',
        ),
        migrations.DeleteModel(
            name='receipt_voucher',
        ),
    ]
