# Generated by Django 4.1 on 2023-03-06 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0041_delete_bank_transcations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='bank_transcations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_voucher', models.IntegerField(blank=True, null=True)),
                ('rec_voucher', models.IntegerField(blank=True, null=True)),
                ('pay_particular', models.IntegerField(blank=True, null=True)),
                ('rec_particular', models.IntegerField(blank=True, null=True)),
                ('bank_account', models.CharField(blank=True, max_length=255, null=True)),
                ('transcation_type', models.CharField(blank=True, max_length=255, null=True)),
                ('instno', models.IntegerField(blank=True, null=True)),
                ('instdate', models.DateField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('acnum', models.CharField(blank=True, max_length=255, null=True)),
                ('ifscode', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='receipt_voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.IntegerField(null=True)),
                ('account', models.CharField(max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('narration', models.CharField(max_length=255, null=True)),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.voucher')),
            ],
        ),
        migrations.CreateModel(
            name='receipt_particulars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particular_id', models.IntegerField(null=True)),
                ('particular', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('rec_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.receipt_voucher')),
            ],
        ),
        migrations.CreateModel(
            name='payment_voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(null=True)),
                ('account', models.CharField(max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('narration', models.CharField(max_length=255, null=True)),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.voucher')),
            ],
        ),
        migrations.CreateModel(
            name='payment_particulars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particular_id', models.IntegerField(null=True)),
                ('particular', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('pay_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.payment_voucher')),
            ],
        ),
    ]
