# Generated by Django 4.1 on 2023-03-06 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0043_remove_credit_note_voucher_stock_itemcreation_godown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit_note',
            name='comp',
        ),
        migrations.DeleteModel(
            name='credit_item',
        ),
        migrations.DeleteModel(
            name='credit_note',
        ),
    ]
