# Generated by Django 4.1 on 2023-03-06 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0045_credit_note_credit_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='debit_note',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.voucher'),
        ),
    ]
