# Generated by Django 4.1.7 on 2023-03-14 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_contra_voucher'),
        ('app1', '0047_bank_transcations_voucher'),
    ]

    operations = [
    ]
